// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBENJbM6zc1md_b8LYYtT7ANo14jsC313E',
    appId: '1:614105344312:android:80a78ae4437caee3bc79cd',
    messagingSenderId: '614105344312',
    projectId: 'vitalcheck-dc088',
    databaseURL: 'https://vitalcheck-dc088-default-rtdb.firebaseio.com',
    storageBucket: 'vitalcheck-dc088.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIrCvf5ZL9tZobMu4mbttAvTmuuWCiRAA',
    appId: '1:614105344312:ios:fcb170d9f095b0abbc79cd',
    messagingSenderId: '614105344312',
    projectId: 'vitalcheck-dc088',
    databaseURL: 'https://vitalcheck-dc088-default-rtdb.firebaseio.com',
    storageBucket: 'vitalcheck-dc088.firebasestorage.app',
    iosBundleId: 'com.example.vitalcheck',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIrCvf5ZL9tZobMu4mbttAvTmuuWCiRAA',
    appId: '1:614105344312:ios:fcb170d9f095b0abbc79cd',
    messagingSenderId: '614105344312',
    projectId: 'vitalcheck-dc088',
    databaseURL: 'https://vitalcheck-dc088-default-rtdb.firebaseio.com',
    storageBucket: 'vitalcheck-dc088.firebasestorage.app',
    iosBundleId: 'com.example.vitalcheck',
  );
}
